export type PageNavKey = "nomos" | "ascension" | "metaphysique" | "aegis" | "caseStudiesIndex";

export const PAGE_NAV_SECTION_IDS: Record<PageNavKey, readonly string[]> = {
  nomos: [
    "hero",
    "symptoms",
    "mechanism",
    "suffering",
    "solutions",
    "protocol",
    "proof",
    "future",
    "founder",
    "roi",
    "guarantee",
    "qualify",
    "faq",
    "audit",
  ],
  ascension: [
    "hero",
    "constat",
    "signes",
    "mechanism",
    "protocol",
    "concrete",
    "results",
    "future",
    "founder",
    "roi",
    "guarantee",
    "qualify",
    "faq",
    "audit",
  ],
  metaphysique: [
    "hero",
    "constat",
    "signes",
    "mechanism",
    "protocol",
    "future",
    "proof",
    "founder",
    "roi",
    "guarantee",
    "qualify",
    "faq",
    "audit",
  ],
  aegis: [
    "hero",
    "positioning",
    "audience",
    "weekly",
    "clinical",
    "philosophy",
    "formats",
    "guarantee",
    "qualify",
    "faq",
    "audit",
  ],
  caseStudiesIndex: ["hero", "studies"],
};
